```{r data generation, echo = FALSE, results = "hide"}
## DATA GENERATION
# total number of balls
total1 <- sample(4:15, 1)
# number of red and blue balls
red1<- sample(2:(total1-2), 1)
blue1 <- total1-red1
# I don't like the answers when both are equal
if (red1==blue1){
  red1 <- red1+1
  blue1 <- blue1-1
}
# decide which colors will be picked each turn
color1 <- sample(c("red","blue"),1)
color2 <- sample(c("red","blue"),1)
# define the type of problem
replace <- FALSE
compound <- TRUE
if (color1=="red"){
  result1 = red1
  red2 <- red1
  blue2 <- blue1
} else {
  result1 = blue1
  red2 <- red1
  blue2 <- blue1
}
if (replace==FALSE){
  total2 <- total1-1
  if (color1=="red"){
  red2 <- (red1-1)
  blue2 <- blue1
} else {
  red2 <- red1
  blue2 <- (blue1-1)
}

} else {
  total2 <- total1
}

if (color2=="red"){
  result2 = red2
} else {
  result2 = blue2
}

# fractions function allows you to display fractions
library(MASS)
#fractions(red/total)
#fractions(blue/total)

# single events

# compound events
# P(X or Y) = P(X)+P(Y) - P(X and Y)
# P(X and Y) = P(X)*P(Y|X) OR P(Y)*P(X|Y)

## QUESTION/ANSWER GENERATION
questions <- character(10)
solutions <- logical(10)
explanations <- character(10)

# four possibilities r,r r,b b,b b,r
# we'll turn each one into a possible answer

# Q1 red, red
questions[1] <- paste(fractions((red1/total1)*(red2/total2)))
  solutions[1] <- (red1/total1)*(red2/total2)==(result1/total1)*(result2/total2)
  explanations[1] <- paste0("The probability of the first event is ",fractions(result1/total1)," The probability of the second event is ",fractions(result2/total2),".")

# Q2 red, blue
questions[2] <- paste(fractions((red1/total1)*(blue2/total2)))
solutions[2] <- (red1/total1)*(blue2/total2)==(result1/total1)*(result2/total2)
explanations[2] <- paste0("The probability of the first event is ",fractions(result1/total1)," The probability of the second event is ",fractions(result2/total2),".")

# Q3 blue, blue
questions[3] <- paste(fractions((blue1/total1)*(blue2/total2)))
solutions[3] <- (blue1/total1)*(blue2/total2)==(result1/total1)*(result2/total2)
explanations[3] <- paste0("The probability of the first event is ",fractions(result1/total1)," The probability of the second event is ",fractions(result2/total2),".")

# Q4 blue, red
questions[4] <- paste(fractions((blue1/total1)*(red2/total2)))
solutions[4] <- (blue1/total1)*(red2/total2)==(result1/total1)*(result2/total2)
explanations[4] <- paste0("The probability of the first event is ",fractions(result1/total1)," The probability of the second event is ",fractions(result2/total2),".")
    
questions[5] <- paste(fractions((red1/total1)))
solutions[5] <- (red1/total1)==(result1/total1)*(result2/total2)
explanations[5] <- paste0("The probability of the first event is ",fractions(result1/total1)," The probability of the second event is ",fractions(result2/total2),".")

questions[6] <- paste(fractions((blue1/total1)))
solutions[6] <- (blue1/total1)==(result1/total1)*(result2/total2)
explanations[6] <- paste0("The probability of the first event is ",fractions(result1/total1)," The probability of the second event is ",fractions(result2/total2),".")

questions[7] <- paste("This is a single event.")
solutions[7] <- compound==FALSE
explanations[7] <- paste0("More than one event takes place in a compound event.")

questions[8] <- paste("This is a compound event.")
solutions[8] <- compound==TRUE
explanations[8] <- paste0("More than one event takes place in a compound event.")

questions[9] <- paste("This is a statistically independent event.")
solutions[9] <- replace==TRUE
explanations[9] <- paste0("Using replacement makes the events independent.")

questions[10] <- paste("This is not a statistically independent event.")
solutions[10] <- replace==FALSE
explanations[10] <- paste0("Using replacement makes the events independent.")

## permute order of solutions/questions
o <- sample(1:10)
questions <- questions[o]
solutions <- solutions[o]
explanations <- explanations[o]

```

Question
========
A bag has `r red1` red balls and `r blue1` blue balls. If you draw one ball out of the bag and then draw another ball without replacing the first, what is the probability of getting a `r color1` ball and then a `r color2` ball? Select the statements that are true.


```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions, markup = "markdown")
```

Solution
========

```{r solutionlist, echo = FALSE, results = "asis"}
answerlist(ifelse(solutions, "True", "False"), explanations, markup = "markdown")
```

Meta-information
================
extype: mchoice
exsolution: `r mchoice2string(solutions)`
exname: Probability1
