```{r data generation, echo = FALSE, results = "hide"}
## DATA GENERATION
total1 <- sample(4:15, 1)
color1 <- sample(c("red","blue"),1)
color2 <- sample(c("red","blue"),1)
red <- sample(2:(total-2), 1)
blue <- total-red
if (red==blue){
  red <- red+1
  blue <- blue-1
}
replace <- TRUE
compound <- TRUE
if (color1=="red"){
  result1 = red
} else {
  result1 = blue
}
if (color2=="red"){
  result2 = red
} else {
  result2 = blue
}
if (replace==FALSE){
  total2 <- total1-1
} else {
  total2 <- total1
}

# fractions function allows you to display fractions
library(MASS)
fractions(red/total)
fractions(blue/total)

# single events

# compound events
# P(X or Y) = P(X)+P(Y) - P(X and Y)
# P(X and Y) = P(X)*P(Y|X) OR P(Y)*P(X|Y)

## QUESTION/ANSWER GENERATION
questions <- character(9)
solutions <- logical(9)
explanations <- character(9)

questions[1] <- paste(fractions(red/total))
  solutions[1] <- red/total==result/total
  explanations[1] <- paste0("The total number of ",color," balls is ", result,". ", "The total number of balls is ", total,".")

questions[2] <- paste(fractions(blue/total))
solutions[2] <- blue/total==result/total
explanations[2] <- paste0("The total number of ",color," balls is ", result,". ", "The total number of balls is ", total,".")

questions[3] <- paste(fractions(red/blue))
solutions[3] <- result/total==red/blue
explanations[3] <- paste0("The total number of ",color," balls is ", result,". ", "The total number of balls is ", total,".")

questions[4] <- paste(fractions(blue/red))
solutions[4] <- result/total==blue/red
explanations[4] <- paste0("The total number of ",color," balls is ", result,". ", "The total number of balls is ", total,".")
    
questions[5] <- paste(fractions((red/total)*(blue/total)))
solutions[5] <- (red/total)*(blue/total)==result/total
explanations[5] <- paste0("The total number of ",color," balls is ", result,". ", "The total number of balls is ", total,".")

questions[6] <- paste("This is a single event.")
solutions[6] <- compound==FALSE
explanations[6] <- paste0("Only one event takes place in a single event.")

questions[7] <- paste("This is a compound event.")
solutions[7] <- compound==TRUE
explanations[7] <- paste0("Only one event takes place in a single event.")

#questions[8] <- paste("This is a statistically independent event.")
#solutions[8] <- compound==FALSE
#explanations[8] <- paste0("Only one event takes place in a single event.")

#questions[9] <- paste("This is a single event.")
#solutions[9] <- compound==FALSE
#explanations[9] <- paste0("Only one event takes place in a single event.")

## permute order of solutions/questions
o <- sample(1:7)
questions <- questions[o]
solutions <- solutions[o]
explanations <- explanations[o]

```

Question
========
A bag has `r red` red balls and `r blue` blue balls. If you draw one ball out of the bag, place it back in the bag, and draw another ball what is the probability of getting a `r color1` ball and then a `r color2` ball? Select the statements that are true.


```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions, markup = "markdown")
```

Solution
========

```{r solutionlist, echo = FALSE, results = "asis"}
answerlist(ifelse(solutions, "True", "False"), explanations, markup = "markdown")
```

Meta-information
================
extype: mchoice
exsolution: `r mchoice2string(solutions)`
exname: Probability1
